import type { Metadata } from "next";
import { unstable_noStore } from "next/cache";
import { Inter } from "next/font/google";
import type { ReactNode } from "react";
import { cn } from "~/lib/utils";
import "./globals.css";

const fontHeading = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

const fontBody = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "local-dev-app",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  sidebar,
}: { children: ReactNode; sidebar: ReactNode }) {
  unstable_noStore();
  return (
    <html lang="en">
      <body
        className={cn("antialiased", fontHeading.variable, fontBody.variable)}
      >
        <div className="grid min-h-screen w-full grid-cols-[300px_1fr] bg-background">
          {sidebar}
          {children}
        </div>
      </body>
    </html>
  );
}
